version: '3'

services:
  vsgan_tensorrt:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: styler00dollar/vsgan_tensorrt:latest_no_avx512
    volumes:
      - ./:/workspace/tensorrt
      - /mnt/fastscratch:/workspace/tensorrt/fastscratch
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
